vm:
  name: developer-vm
  box: bento/ubuntu-22.04
  hostname: developer-vm
  network:
    ip: 192.168.56.4
  requirements:
    core: 2
    #MB
    memory: 5000
docker:
  install: false
#  set specific version or empty (default version)
#  version: 5:24.0.0-1~ubuntu.22.04~jammy
kubernetes:
  install: true
