vm:
  name: developer-vm
  box: bento/ubuntu-22.04
  hostname: developer-vm
  network:
    ip: 192.168.56.4
  requirements:
    core: 2
    memory: 5000 #MB
docker:
  install: false
#  version: 5:24.0.0-1~ubuntu.22.04~jammy #set specific version or default
kubernetes:
  install: true
  version: 1.27.3-00 #https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/README.md
  cri-o:
    version: 1.27
    os: xUbuntu_22.04 #https://github.com/cri-o/cri-o/blob/main/install.md#apt-based-operating-systems-1
  extensions:
    rabbitmq:
      install: true
      image: rabbitmq:3.7-management
      access: #access from host
        broker:
          port: 9000
        manager:
          port: 9001
