
Vagrant.configure("2") do |config|

  #basic
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "developer-vm"

  #network
  config.vm.network "private_network", ip: "10.10.10.10"

  #ssh private key issue
  config.ssh.insert_key = false

 config.vm.provider "virtualbox" do |vb|
   vb.name = "developer-vm"
   vb.cpus = 4
   vb.memory = "5000"

#   config.vm.provision "shell", path: "script/install_docker.sh"
#   config.vm.provision "shell", path: "script/kubernetes.sh"

   end


end
