require "yaml"
settings = YAML.load_file "settings.yaml"

Vagrant.configure("2") do |config|

  #ssh private key issue
  #default true
  #necessary ?
#  config.ssh.insert_key = false

 config.vm.define "master" do |master|
    master.vm.box = settings["vm"]["box"]
    master.vm.hostname = settings["vm"]["hostname"]
    #network
    master.vm.network "private_network", ip: settings["vm"]["network"]["ip"]

   if settings["docker"]["install"] == true
    master.vm.provision "shell",
      env: {
        "VERSION" => settings["docker"]["version"],
      },
      path: "scripts/docker.sh"
   end

#   if settings["kubernetes"]["install"] == true
#    master.vm.provision "shell",
#      env: {
#        "VERSION" => settings["kubernetes"]["version"],
#      },
#      path: "scripts/kubernetes.sh"
#   end

  master.vm.provider "virtualbox" do |vb|
    vb.name = settings["vm"]["name"]
    vb.cpus = settings["vm"]["requirements"]["core"]
    vb.memory = settings["vm"]["requirements"]["memory"]
  end
 end


end
