apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-broker
  labels:
    role: infrastructure
    type: message-broker
    app: rabbitmq
spec:
  type: NodePort
  selector:
    role: infrastructure
    type: message-broker
    app: rabbitmq
  ports:
    - name: broker
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: ${BROKER_PORT}
